---
- name: Download and extract split tar files if they do not exist
  hosts: localhost
  vars_files:
    - all.yaml  # This includes the file that contains your variables

  tasks:
    - name: Check if the sentinel file exists for {{ item.url }}
      stat:
        path: "{{ item.sentinel }}"
      register: sentinel_status
      loop: "{{ files }}"

    - block:
        - name: Download {{ item.url }}
          get_url:
            url: "{{ item.url }}"
            dest: "{{ item.dest }}"
            timeout: 600

        - name: Extract {{ item.dest }}
          unarchive:
            src: "{{ item.dest }}"
            dest: "{{ extract_path }}"
            remote_src: yes

        - name: Remove tar file {{ item.dest }}
          file:
            path: "{{ item.dest }}"
            state: absent

        - name: Creating sentinel {{ item.sentinel }}
          file:
            path: "{{ item.sentinel }}"
            state: touch

      rescue:
        - name: Print error message
          ansible.builtin.debug:
            msg: 'An error occurred while processing {{ item.url }}.'

      always:
        - name: Print always message
          ansible.builtin.debug:
            msg: 'Finished processing {{ item.url }}.'

      when: item.stat.exists == False
      loop: "{{ sentinel_status.results }}"
