---
- name: Download and extract split tar files if they do not exist
  hosts: localhost
  vars_files:
    - all.yaml  # This includes the file that contains your variables

  tasks:
    - name: Check if the sentinel file exists for {{ item.url }}
      stat:
        path: "{{ item.sentinel }}"
      register: sentinel_status
      with_items: "{{ files }}"

    - block:
        - name: Downloading {{ item.item.url }}
          get_url:
            url: "{{ item.item.url }}"
            dest: "{{ item.item.dest }}"
            timeout: 600
          when: item.stat.exists == False

        - name: Extracting {{ item.item.dest }}
          unarchive:
            src: "{{ item.item.dest }}"
            dest: "{{ extract_path }}"
            remote_src: yes
          when: item.stat.exists == False

        - name: Removing tar file {{ item.item.dest }}
          file:
            path: "{{ item.item.dest }}"
            state: absent
          when: item.stat.exists == False

        - name: Creating sentinel {{ item.item.sentinel }}
          file:
            path: "{{ item.item.sentinel }}"
            state: touch
          when: item.stat.exists == False

      with_items: "{{ sentinel_status.results }}"
